documentation:
  swagger:
    services:
      -
        name: Calendar Service
        url: /specs/calendar-service/groups/default
        version: 2.0
      -
        name: Tag Service
        url: /specs/tag-service/groups/api-v1
        version: 2.0
      - 
        name: Swagger Aggregate
        url: /specs/localhost/groups/default
        version: 2.0